services:
  gateway-postgres:
    image: postgres:16-alpine
    container_name: lsp_gateway_postgres
    environment:
      POSTGRES_DB: lsp_gateway
      POSTGRES_USER: lsp_gateway_app
      POSTGRES_PASSWORD: 1111
    ports:
      - "15432:5432"
    volumes:
      - gateway_postgres_data:/var/lib/postgresql/data

  gateway-redis:
    image: redis:7-alpine
    container_name: lsp_gateway_redis
    ports:
      - "6379:6379"

volumes:
  gateway_postgres_data:
